package dev.sweety.sql4j.impl.connection.dialect;

import dev.sweety.sql4j.api.connection.dialect.Dialect;
import dev.sweety.sql4j.api.obj.ForeignKey;

public class PostgreSQLDialect implements Dialect {

    @Override
    public String name() {
        return "postgresql";
    }

    @Override
    public String sqlType(Class<?> type) {
        if (type == int.class || type == Integer.class)
            return "INTEGER";

        if (type == long.class || type == Long.class)
            return "BIGINT";

        if (type == boolean.class || type == Boolean.class)
            return "BOOLEAN";

        if (type == float.class || type == Float.class)
            return "REAL";

        if (type == double.class || type == Double.class)
            return "DOUBLE PRECISION";

        if (type == byte[].class)
            return "BYTEA";

        return "VARCHAR(255)";
    }

    @Override
    public String autoIncrement() {
        // In PostgreSQL, using SERIAL or GENERATED ALWAYS AS IDENTITY is handled at column definition.
        // For simplicity in this `sqlType` + `autoIncrement` string concatenation model,
        // we might return "GENERATED BY DEFAULT AS IDENTITY" if the caller appends it.
        // But historically SQL4J seems to expect a modifier.
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public String foreignKeyAction(ForeignKey.Action action) {
        return switch (action) {
            case CASCADE -> "CASCADE";
            case SET_NULL -> "SET NULL";
            case RESTRICT, NO_ACTION -> "RESTRICT";
        };
    }
}

