"hub":
  "host": "127.0.0.1"
  "port": 4000
"services":
  "database":
    "count": 1
    "ports": [5100]
    "hosts": ["127.0.0.1"]
  "service":
    "count": 2
    "ports": [5200, 5202]
    "hosts": ["127.0.0.1", "127.0.0.1"]
  "lobby":
    "count": 2
    "externalPorts": [5003, 5005]
    "ports": [5002, 5004]
    "hosts": ["127.0.0.1", "127.0.0.1"]
