package dev.sweety.transform.vm;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.WeakHashMap;

import static dev.sweety.transform.vm.VMSupport.paramSlotWidths;
import static dev.sweety.transform.vm.VMSupport.paramTypeTags;
import static dev.sweety.transform.vm.VMSupport.readString;
import static dev.sweety.transform.vm.VMSupport.unboxD;
import static dev.sweety.transform.vm.VMSupport.unboxF;
import static dev.sweety.transform.vm.VMSupport.unboxI;
import static dev.sweety.transform.vm.VMSupport.unboxL;

/**
 * Lightweight stack-based VM that executes method bodies compiled to
 * {@link VmOp} bytecode by the build-time {@link dev.sweety.transform.engine.transformer.virtualize.VMCompiler}.
 *
 * <p><strong>Runtime model (de-boxed):</strong>
 * <ul>
 *   <li>{@link VMLocals} — dual {@code long[]}/{@code Object[]} local-variable table, index 0 is
 *       {@code this} (null for static methods)</li>
 *   <li>{@link VMStack} — dual {@code long[]}/{@code Object[]} operand stack, shared index per pushed
 *       value; no boxing except at the unavoidable reflection-API boundary (see {@link ReflectionOps})</li>
 *   <li>Method/field dispatch via reflection — cached in a static WeakHashMap per bytecode array</li>
 * </ul>
 *
 * <p>The decode/dispatch loop lives here; the actual op families are split out by responsibility
 * into {@link ArithmeticOps} (int/long/float/double math+conversion), {@link StackOps}
 * (POP/DUP/SWAP family), {@link ReflectionOps} (invoke/field access), {@link ObjectOps}
 * (NEW/CHECKCAST/INSTANCEOF/ARRAYLENGTH/THROW/monitor) and {@link ArrayOps} (array load/store/alloc).
 *
 * <p>Invoked by the stub generated by {@link dev.sweety.transform.engine.transformer.virtualize.VirtualizerTransformer}:
 * <pre>
 *   Object result = VMInterpreter.execute(this_or_null, args, BYTECODE);
 * </pre>
 */
public final class VMInterpreter {

    private VMInterpreter() {}

    // Per-bytecode reflection cache: method/field lookups are cached after first execution.
    private static final Map<byte[], Map<String, Object>> CACHE =
            Collections.synchronizedMap(new WeakHashMap<>());

    // Bound once at client bootstrap to bridge the live session keystream (client/src, a module this
    // one can't compile-depend on). Unbound = neutral (tests, server-side compile path) — the same
    // "no session infrastructure here" treatment SessionKeystream's own dev-bypass flag gets, NOT
    // treated as a stale session.
    private static volatile SessionFoldSource sessionFold;

    /** Bind the live session bridge once at client bootstrap. Not for test/dev use — see class javadoc. */
    public static void bindSessionFold(SessionFoldSource source) {
        sessionFold = source;
    }

    /**
     * Execute VM bytecode.
     *
     * @param self    {@code this} for instance methods; {@code null} for static
     * @param args    method arguments (does not include {@code this}) — boxed by the JVM's own calling
     *                convention at the generated stub's call site; unboxed here into {@link VMLocals}
     * @param code    compiled VM bytecode produced by {@link dev.sweety.transform.engine.transformer.virtualize.VMCompiler}
     * @return        boxed return value, or {@code null} for void
     */
    public static Object execute(Object self, Object[] args, byte[] code) {
        // Gated delivery (Layer 1): the storage field stays null until the client requests+decrypts
        // the real bytecode post-first-heartbeat (see VirtualBytecodeService, server-side). A jar
        // extracted/replayed without ever completing that exchange has no bytecode to run at all.
        if (code == null || code.length == 0) {
            throw new IllegalStateException("Virtualized method has no bytecode — session not yet live");
        }

        final ByteBuffer buf = ByteBuffer.wrap(code);
        buf.order(ByteOrder.BIG_ENDIAN);

        // Header: maxLocals + method descriptor (drives JVM slot layout for long/double params) +
        // per-method salt for the session-fold entanglement check below.
        final int maxLocals = buf.getShort() & 0xFFFF;
        final String desc = readString(buf);
        final int methodSalt = buf.getInt();

        // Entangle with the live session, if one is bound. A bound-but-stale session aborts loudly —
        // no separate patchable branch, same property SessionKeystream.kill() gives other consumers.
        // Unbound (no hook installed) is neutral and proceeds unaffected.
        final SessionFoldSource fold = sessionFold;
        if (fold != null && !fold.fresh()) {
            throw new IllegalStateException("Virtualized method requires a live session");
        }

        // Place args at their real JVM local slots: long/double consume TWO slots each, so a
        // sequential one-slot-per-arg layout would misread every local after a long/double param.
        // Each arg is routed to VMLocals' `prim` or `ref` array per its descriptor tag — the args
        // array itself stays boxed (unavoidable: it crossed the generated stub's real Java call).
        final VMLocals locals = new VMLocals(maxLocals);
        int slot = 0;
        if (self != null) locals.ref[slot++] = self; // `this` is always one slot, always a reference
        if (args != null) {
            final char[] tags = paramTypeTags(desc);
            final int[] widths = paramSlotWidths(desc);
            for (int i = 0; i < args.length; i++) {
                final char tag = i < tags.length ? tags[i] : 'L';
                switch (tag) {
                    case 'J' -> locals.prim[slot] = unboxL(args[i]);
                    case 'F' -> locals.prim[slot] = Float.floatToRawIntBits(unboxF(args[i]));
                    case 'D' -> locals.prim[slot] = Double.doubleToRawLongBits(unboxD(args[i]));
                    case 'L' -> locals.ref[slot] = args[i];
                    default  -> locals.prim[slot] = unboxI(args[i]); // Z/B/C/S/I
                }
                slot += (i < widths.length ? widths[i] : 1);
            }
        }

        final VMStack stack = new VMStack(16); // grows as needed; most methods never exceed this
        final Map<String, Object> cache = CACHE.computeIfAbsent(code, k -> new HashMap<>());

        try {
            return runLoop(buf, locals, stack, cache);
        } catch (Throwable t) {
            throw new RuntimeException("VM execution error", t);
        }
    }

    private static Object runLoop(ByteBuffer buf, VMLocals locals, VMStack stack,
                                   Map<String, Object> cache) throws Exception {
        while (buf.hasRemaining()) {
            final VmOp op = VmOp.fromCode(buf.get());

            switch (op) {
                // ── Constants ─────────────────────────────────────────────────
                case PUSH_NULL   -> stack.pushRef(null);
                case PUSH_INT    -> stack.pushI(buf.getInt());
                case PUSH_LONG   -> stack.pushL(buf.getLong());
                case PUSH_FLOAT  -> stack.pushF(Float.intBitsToFloat(buf.getInt()));
                case PUSH_DOUBLE -> stack.pushD(Double.longBitsToDouble(buf.getLong()));
                case PUSH_STRING -> stack.pushRef(readString(buf));
                case PUSH_CLASS  -> stack.pushRef(Class.forName(readString(buf).replace('/', '.')));

                // ── Locals ────────────────────────────────────────────────────
                case LOAD_PRIM  -> stack.pushSlot(locals.prim[buf.getShort() & 0xFFFF], null);
                case LOAD_REF   -> stack.pushRef(locals.ref[buf.getShort() & 0xFFFF]);
                case STORE_PRIM -> locals.prim[buf.getShort() & 0xFFFF] = stack.popL();
                case STORE_REF  -> locals.ref[buf.getShort() & 0xFFFF] = stack.popRef();

                // ── Arithmetic / conversions ─────────────────────────────────
                case IADD, ISUB, IMUL, IDIV, IREM, INEG, IAND, IOR, IXOR, ISHL, ISHR, IUSHR,
                     LADD, LSUB, LMUL, LDIV, LREM, LNEG, LAND, LOR, LXOR, LCMP,
                     FADD, FSUB, FMUL, FDIV, FREM, FNEG, FCMPL, FCMPG,
                     DADD, DSUB, DMUL, DDIV, DREM, DNEG, DCMPL, DCMPG,
                     I2L, I2F, I2D, I2B, I2C, I2S, L2I, L2F, L2D, F2I, F2L, F2D, D2I, D2L, D2F
                        -> ArithmeticOps.execute(op, stack);

                // ── Control flow ──────────────────────────────────────────────
                case GOTO       -> buf.position(buf.getInt());
                case IF_NULL    -> { int t = buf.getInt(); if (stack.popRef() == null) buf.position(t); }
                case IF_NONNULL -> { int t = buf.getInt(); if (stack.popRef() != null) buf.position(t); }
                case IFEQ       -> { int t = buf.getInt(); if (stack.popI() == 0) buf.position(t); }
                case IFNE       -> { int t = buf.getInt(); if (stack.popI() != 0) buf.position(t); }
                case IFLT       -> { int t = buf.getInt(); if (stack.popI() < 0)  buf.position(t); }
                case IFGE       -> { int t = buf.getInt(); if (stack.popI() >= 0) buf.position(t); }
                case IFGT       -> { int t = buf.getInt(); if (stack.popI() > 0)  buf.position(t); }
                case IFLE       -> { int t = buf.getInt(); if (stack.popI() <= 0) buf.position(t); }
                case IF_ICMPEQ  -> { int t = buf.getInt(); int b = stack.popI(); int a = stack.popI(); if (a == b) buf.position(t); }
                case IF_ICMPNE  -> { int t = buf.getInt(); int b = stack.popI(); int a = stack.popI(); if (a != b) buf.position(t); }
                case IF_ICMPLT  -> { int t = buf.getInt(); int b = stack.popI(); int a = stack.popI(); if (a < b)  buf.position(t); }
                case IF_ICMPGE  -> { int t = buf.getInt(); int b = stack.popI(); int a = stack.popI(); if (a >= b) buf.position(t); }
                case IF_ICMPGT  -> { int t = buf.getInt(); int b = stack.popI(); int a = stack.popI(); if (a > b)  buf.position(t); }
                case IF_ICMPLE  -> { int t = buf.getInt(); int b = stack.popI(); int a = stack.popI(); if (a <= b) buf.position(t); }
                case IF_ACMPEQ  -> { int t = buf.getInt(); Object b = stack.popRef(); Object a = stack.popRef(); if (a == b) buf.position(t); }
                case IF_ACMPNE  -> { int t = buf.getInt(); Object b = stack.popRef(); Object a = stack.popRef(); if (a != b) buf.position(t); }

                // ── Return ────────────────────────────────────────────────────
                case RETURN  -> { return null; }
                case IRETURN -> { return stack.popI(); }
                case LRETURN -> { return stack.popL(); }
                case FRETURN -> { return stack.popF(); }
                case DRETURN -> { return stack.popD(); }
                case ARETURN -> { return stack.popRef(); }

                // ── Method invocation ─────────────────────────────────────────
                case INVOKE_VIRTUAL   -> ReflectionOps.executeInvoke(stack, cache, buf, false, true,  false);
                case INVOKE_STATIC    -> ReflectionOps.executeInvoke(stack, cache, buf, true,  false, false);
                case INVOKE_SPECIAL   -> ReflectionOps.executeInvoke(stack, cache, buf, false, false, false);
                case INVOKE_INTERFACE -> ReflectionOps.executeInvoke(stack, cache, buf, false, true,  true);

                // ── Field access ──────────────────────────────────────────────
                case GET_FIELD  -> ReflectionOps.executeGetField(stack, cache, buf, false);
                case PUT_FIELD  -> ReflectionOps.executePutField(stack, cache, buf, false);
                case GET_STATIC -> ReflectionOps.executeGetField(stack, cache, buf, true);
                case PUT_STATIC -> ReflectionOps.executePutField(stack, cache, buf, true);

                // ── Stack manipulation ────────────────────────────────────────
                case POP, POP2_CAT1, POP2_CAT2, DUP, DUP_X1, DUP_X2_CAT1, DUP_X2_CAT2,
                     DUP2_CAT1, DUP2_CAT2, SWAP -> StackOps.execute(op, stack);

                // ── Object operations ─────────────────────────────────────────
                case NEW         -> ObjectOps.executeNew(stack, buf);
                case CHECKCAST   -> ObjectOps.executeCheckCast(stack, cache, buf);
                case INSTANCEOF  -> ObjectOps.executeInstanceOf(stack, cache, buf);
                case ARRAYLENGTH -> ObjectOps.executeArrayLength(stack);
                case THROW       -> ObjectOps.executeThrow(stack);
                case MONENTER, MONEXIT -> stack.popRaw(1); // ignored — not safe to honor real monitor semantics in the VM

                // ── Array operations ──────────────────────────────────────────
                case AALOAD, AASTORE, IALOAD, IASTORE, LALOAD, LASTORE, FALOAD, FASTORE,
                     DALOAD, DASTORE, BALOAD, BASTORE, CALOAD, CASTORE, SALOAD, SASTORE,
                     NEWARRAY, ANEWARRAY -> ArrayOps.execute(op, stack, cache, buf);
            }
        }
        return null; // implicit void return
    }
}
