package dev.sweety.transform.vm;

import java.lang.reflect.*;
import java.nio.*;
import java.util.*;

/**
 * Lightweight stack-based VM that executes method bodies compiled to
 * {@link VMOpcode} bytecode by the build-time {@link dev.sweety.transform.engine.transformer.virtualize.VMCompiler}.
 *
 * <p><strong>Runtime model:</strong>
 * <ul>
 *   <li>Object[] locals — index 0 is {@code this} (null for static methods)</li>
 *   <li>Deque&lt;Object&gt; stack — operand stack, all values boxed</li>
 *   <li>Method dispatch via reflection — cached in a static WeakHashMap per bytecode array</li>
 * </ul>
 *
 * <p>Invoked by the stub generated by {@link dev.sweety.transform.engine.transformer.virtualize.VirtualizerTransformer}:
 * <pre>
 *   Object result = VMInterpreter.execute(this_or_null, args, BYTECODE);
 * </pre>
 */
public final class VMInterpreter {

    private VMInterpreter() {}

    // Per-bytecode reflection cache: method/field lookups are cached after first execution.
    private static final Map<byte[], Map<String, Object>> CACHE =
            Collections.synchronizedMap(new WeakHashMap<>());

    /**
     * Execute VM bytecode.
     *
     * @param self    {@code this} for instance methods; {@code null} for static
     * @param args    method arguments (does not include {@code this})
     * @param code    compiled VM bytecode produced by {@link dev.sweety.transform.engine.transformer.virtualize.VMCompiler}
     * @return        boxed return value, or {@code null} for void
     */
    public static Object execute(Object self, Object[] args, byte[] code) {
        final ByteBuffer buf = ByteBuffer.wrap(code);
        buf.order(ByteOrder.BIG_ENDIAN);

        // Build local variable array: [this?, arg0, arg1, ...]
        // The bytecode reserves space declared in the first 2 bytes of the code
        buf.mark();
        final int maxLocals = buf.getShort() & 0xFFFF;
        buf.mark(); // we will NOT reset; maxLocals header is consumed

        final Object[] locals = new Object[maxLocals];
        int idx = 0;
        if (self != null) locals[idx++] = self;
        if (args != null) for (Object a : args) locals[idx++] = a;

        final Deque<Object> stack = new ArrayDeque<>(32);

        // Reflection cache for this bytecode array
        final Map<String, Object> cache = CACHE.computeIfAbsent(code, k -> new HashMap<>());

        try {
            while (buf.hasRemaining()) {
                final byte op = buf.get();

                switch (op & 0xFF) {

                    // ── Constants ─────────────────────────────────────────────
                    case 0x00: stack.push(null); break;
                    case 0x01: stack.push(buf.getInt()); break;
                    case 0x02: stack.push(buf.getLong()); break;
                    case 0x03: stack.push(Float.intBitsToFloat(buf.getInt())); break;
                    case 0x04: stack.push(Double.longBitsToDouble(buf.getLong())); break;
                    case 0x05: stack.push(readString(buf)); break;
                    case 0x06: stack.push(Class.forName(readString(buf).replace('/', '.'))); break;

                    // ── Locals ────────────────────────────────────────────────
                    case 0x10: stack.push(locals[buf.getShort() & 0xFFFF]); break;
                    case 0x11: { int vi = buf.getShort() & 0xFFFF; locals[vi] = stack.pop(); break; }

                    // ── Integer arithmetic ────────────────────────────────────
                    case 0x20: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 + b2); break; }
                    case 0x21: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 - b2); break; }
                    case 0x22: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 * b2); break; }
                    case 0x23: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 / b2); break; }
                    case 0x24: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 % b2); break; }
                    case 0x25: stack.push(-unboxI(stack.pop())); break;
                    case 0x26: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 & b2); break; }
                    case 0x27: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 | b2); break; }
                    case 0x28: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 ^ b2); break; }
                    case 0x29: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 << b2); break; }
                    case 0x2A: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 >> b2); break; }
                    case 0x2B: { int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); stack.push(a2 >>> b2); break; }

                    // ── Long arithmetic ───────────────────────────────────────
                    case 0x30: { long b2 = unboxL(stack.pop()); long a2 = unboxL(stack.pop()); stack.push(a2 + b2); break; }
                    case 0x31: { long b2 = unboxL(stack.pop()); long a2 = unboxL(stack.pop()); stack.push(a2 - b2); break; }
                    case 0x32: { long b2 = unboxL(stack.pop()); long a2 = unboxL(stack.pop()); stack.push(a2 * b2); break; }
                    case 0x33: { long b2 = unboxL(stack.pop()); long a2 = unboxL(stack.pop()); stack.push(a2 / b2); break; }
                    case 0x34: { long b2 = unboxL(stack.pop()); long a2 = unboxL(stack.pop()); stack.push(a2 % b2); break; }
                    case 0x35: stack.push(-unboxL(stack.pop())); break;
                    case 0x36: { long b2 = unboxL(stack.pop()); long a2 = unboxL(stack.pop()); stack.push(a2 & b2); break; }
                    case 0x37: { long b2 = unboxL(stack.pop()); long a2 = unboxL(stack.pop()); stack.push(a2 | b2); break; }
                    case 0x38: { long b2 = unboxL(stack.pop()); long a2 = unboxL(stack.pop()); stack.push(a2 ^ b2); break; }
                    case 0x39: { long b2 = unboxL(stack.pop()); long a2 = unboxL(stack.pop()); stack.push(Long.compare(a2, b2)); break; }

                    // ── Float arithmetic ──────────────────────────────────────
                    case 0x40: { float b2 = unboxF(stack.pop()); float a2 = unboxF(stack.pop()); stack.push(a2 + b2); break; }
                    case 0x41: { float b2 = unboxF(stack.pop()); float a2 = unboxF(stack.pop()); stack.push(a2 - b2); break; }
                    case 0x42: { float b2 = unboxF(stack.pop()); float a2 = unboxF(stack.pop()); stack.push(a2 * b2); break; }
                    case 0x43: { float b2 = unboxF(stack.pop()); float a2 = unboxF(stack.pop()); stack.push(a2 / b2); break; }
                    case 0x44: { float b2 = unboxF(stack.pop()); float a2 = unboxF(stack.pop()); stack.push(a2 % b2); break; }
                    case 0x45: stack.push(-unboxF(stack.pop())); break;
                    case 0x46: { float b2 = unboxF(stack.pop()); float a2 = unboxF(stack.pop()); stack.push(Float.compare(a2, b2) < 0 ? -1 : Float.compare(a2, b2) == 0 ? 0 : 1); break; }
                    case 0x47: { float b2 = unboxF(stack.pop()); float a2 = unboxF(stack.pop()); stack.push(Float.compare(a2, b2) > 0 ? 1 : Float.compare(a2, b2) == 0 ? 0 : -1); break; }

                    // ── Double arithmetic ─────────────────────────────────────
                    case 0x50: { double b2 = unboxD(stack.pop()); double a2 = unboxD(stack.pop()); stack.push(a2 + b2); break; }
                    case 0x51: { double b2 = unboxD(stack.pop()); double a2 = unboxD(stack.pop()); stack.push(a2 - b2); break; }
                    case 0x52: { double b2 = unboxD(stack.pop()); double a2 = unboxD(stack.pop()); stack.push(a2 * b2); break; }
                    case 0x53: { double b2 = unboxD(stack.pop()); double a2 = unboxD(stack.pop()); stack.push(a2 / b2); break; }
                    case 0x54: { double b2 = unboxD(stack.pop()); double a2 = unboxD(stack.pop()); stack.push(a2 % b2); break; }
                    case 0x55: stack.push(-unboxD(stack.pop())); break;
                    case 0x56: { double b2 = unboxD(stack.pop()); double a2 = unboxD(stack.pop()); stack.push(Double.compare(a2, b2) < 0 ? -1 : Double.compare(a2, b2) == 0 ? 0 : 1); break; }
                    case 0x57: { double b2 = unboxD(stack.pop()); double a2 = unboxD(stack.pop()); stack.push(Double.compare(a2, b2) > 0 ? 1 : Double.compare(a2, b2) == 0 ? 0 : -1); break; }

                    // ── Control flow ──────────────────────────────────────────
                    case 0x60: { int target = buf.getInt(); buf.position(target); break; } // GOTO
                    case 0x61: { int target = buf.getInt(); if (stack.pop() == null) buf.position(target); break; } // IF_NULL
                    case 0x62: { int target = buf.getInt(); if (stack.pop() != null) buf.position(target); break; } // IF_NONNULL
                    case 0x63: { int target = buf.getInt(); if (unboxI(stack.pop()) == 0) buf.position(target); break; } // IFEQ
                    case 0x64: { int target = buf.getInt(); if (unboxI(stack.pop()) != 0) buf.position(target); break; } // IFNE
                    case 0x65: { int target = buf.getInt(); if (unboxI(stack.pop()) < 0)  buf.position(target); break; } // IFLT
                    case 0x66: { int target = buf.getInt(); if (unboxI(stack.pop()) >= 0) buf.position(target); break; } // IFGE
                    case 0x67: { int target = buf.getInt(); if (unboxI(stack.pop()) > 0)  buf.position(target); break; } // IFGT
                    case 0x68: { int target = buf.getInt(); if (unboxI(stack.pop()) <= 0) buf.position(target); break; } // IFLE
                    case 0x69: { int target = buf.getInt(); int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); if (a2 == b2) buf.position(target); break; }
                    case 0x6A: { int target = buf.getInt(); int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); if (a2 != b2) buf.position(target); break; }
                    case 0x6B: { int target = buf.getInt(); int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); if (a2 < b2)  buf.position(target); break; }
                    case 0x6C: { int target = buf.getInt(); int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); if (a2 >= b2) buf.position(target); break; }
                    case 0x6D: { int target = buf.getInt(); int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); if (a2 > b2)  buf.position(target); break; }
                    case 0x6E: { int target = buf.getInt(); int b2 = unboxI(stack.pop()); int a2 = unboxI(stack.pop()); if (a2 <= b2) buf.position(target); break; }
                    case 0x6F: { int target = buf.getInt(); Object b2 = stack.pop(); Object a2 = stack.pop(); if (a2 == b2)  buf.position(target); break; }
                    case 0x70: { int target = buf.getInt(); Object b2 = stack.pop(); Object a2 = stack.pop(); if (a2 != b2)  buf.position(target); break; }

                    // ── Return ────────────────────────────────────────────────
                    case 0x80: return null;
                    case 0x81: return stack.pop();  // IRETURN
                    case 0x82: return stack.pop();  // LRETURN
                    case 0x83: return stack.pop();  // FRETURN
                    case 0x84: return stack.pop();  // DRETURN
                    case 0x85: return stack.pop();  // ARETURN

                    // ── Method invocation ─────────────────────────────────────
                    case 0x90: executeInvoke(stack, cache, buf, false, true,  false); break; // INVOKE_VIRTUAL
                    case 0x91: executeInvoke(stack, cache, buf, true,  false, false); break; // INVOKE_STATIC
                    case 0x92: executeInvoke(stack, cache, buf, false, false, false); break; // INVOKE_SPECIAL
                    case 0x93: executeInvoke(stack, cache, buf, false, true,  true);  break; // INVOKE_INTERFACE

                    // ── Field access ──────────────────────────────────────────
                    case 0xA0: executeGetField(stack, cache, buf, false); break;
                    case 0xA1: executePutField(stack, cache, buf, false); break;
                    case 0xA2: executeGetField(stack, cache, buf, true);  break;
                    case 0xA3: executePutField(stack, cache, buf, true);  break;

                    // ── Stack manipulation ────────────────────────────────────
                    case 0xB0: stack.pop(); break;
                    case 0xB1: { stack.pop(); stack.pop(); break; } // POP2 (simplified)
                    case 0xB2: { Object v = stack.peek(); stack.push(v); break; } // DUP
                    case 0xB3: { Object v = stack.pop(); Object under = stack.pop(); stack.push(v); stack.push(under); stack.push(v); break; } // DUP_X1
                    case 0xB4: { Object v = stack.pop(); stack.push(v); stack.push(v); break; } // DUP2 simplified
                    case 0xB5: { Object a2 = stack.pop(); Object b2 = stack.pop(); stack.push(a2); stack.push(b2); break; } // SWAP
                    case 0xB6: { Object top = stack.pop(); stack.push(top); stack.push(top); break; } // DUP_X2 simplified

                    // ── Type conversions ──────────────────────────────────────
                    case 0xC0: stack.push((long) unboxI(stack.pop())); break;  // I2L
                    case 0xC1: stack.push((float) unboxI(stack.pop())); break; // I2F
                    case 0xC2: stack.push((double) unboxI(stack.pop())); break;// I2D
                    case 0xC3: stack.push((int)(byte) unboxI(stack.pop())); break;  // I2B
                    case 0xC4: stack.push((int)(char) unboxI(stack.pop())); break;  // I2C
                    case 0xC5: stack.push((int)(short) unboxI(stack.pop())); break; // I2S
                    case 0xC6: stack.push((int) unboxL(stack.pop())); break;   // L2I
                    case 0xC7: stack.push((float) unboxL(stack.pop())); break; // L2F
                    case 0xC8: stack.push((double) unboxL(stack.pop())); break;// L2D
                    case 0xC9: stack.push((int) unboxF(stack.pop())); break;   // F2I
                    case 0xCA: stack.push((long) unboxF(stack.pop())); break;  // F2L
                    case 0xCB: stack.push((double) unboxF(stack.pop())); break;// F2D
                    case 0xCC: stack.push((int) unboxD(stack.pop())); break;   // D2I
                    case 0xCD: stack.push((long) unboxD(stack.pop())); break;  // D2L
                    case 0xCE: stack.push((float) unboxD(stack.pop())); break; // D2F

                    // ── Object operations ─────────────────────────────────────
                    case 0xD0: { // NEW
                        String cls = readString(buf);
                        Class<?> c = classFor(cache, cls);
                        // Pushed un-initialized — INVOKE_SPECIAL <init> follows
                        stack.push(sun.misc.Unsafe.class); // placeholder; real alloc on invokespecial
                        stack.push(c); // stash class for the dup+invokespecial that follows
                        break;
                    }
                    case 0xD1: { // CHECKCAST
                        String cls = readString(buf);
                        Object v = stack.peek();
                        if (v != null) classFor(cache, cls).cast(v); // throws CCE if wrong
                        break;
                    }
                    case 0xD2: { // INSTANCEOF
                        String cls = readString(buf);
                        Object v = stack.pop();
                        stack.push(v != null && classFor(cache, cls).isInstance(v) ? 1 : 0);
                        break;
                    }
                    case 0xD3: stack.push(Array.getLength(stack.pop())); break; // ARRAYLENGTH
                    case 0xD4: { Object ex = stack.pop(); if (ex instanceof Throwable t) throw t; throw new RuntimeException(String.valueOf(ex)); } // THROW
                    case 0xD5: { /* MONENTER — ignored; not safe in VM context */ stack.pop(); break; }
                    case 0xD6: { /* MONEXIT  — ignored */ stack.pop(); break; }

                    // ── Array operations ──────────────────────────────────────
                    case 0xE0: { int i = unboxI(stack.pop()); Object arr = stack.pop(); stack.push(Array.get(arr, i)); break; }   // AALOAD
                    case 0xE1: { Object val = stack.pop(); int i = unboxI(stack.pop()); Object arr = stack.pop(); Array.set(arr, i, val); break; } // AASTORE
                    case 0xE2: { int i = unboxI(stack.pop()); Object arr = stack.pop(); stack.push(Array.getInt(arr, i)); break; } // IALOAD
                    case 0xE3: { int val = unboxI(stack.pop()); int i = unboxI(stack.pop()); Object arr = stack.pop(); Array.setInt(arr, i, val); break; } // IASTORE
                    case 0xE4: { int i = unboxI(stack.pop()); Object arr = stack.pop(); stack.push(Array.getLong(arr, i)); break; }
                    case 0xE5: { long val = unboxL(stack.pop()); int i = unboxI(stack.pop()); Object arr = stack.pop(); Array.setLong(arr, i, val); break; }
                    case 0xE6: { int i = unboxI(stack.pop()); Object arr = stack.pop(); stack.push(Array.getFloat(arr, i)); break; }
                    case 0xE7: { float val = unboxF(stack.pop()); int i = unboxI(stack.pop()); Object arr = stack.pop(); Array.setFloat(arr, i, val); break; }
                    case 0xE8: { int i = unboxI(stack.pop()); Object arr = stack.pop(); stack.push(Array.getDouble(arr, i)); break; }
                    case 0xE9: { double val = unboxD(stack.pop()); int i = unboxI(stack.pop()); Object arr = stack.pop(); Array.setDouble(arr, i, val); break; }
                    case 0xEA: { int i = unboxI(stack.pop()); Object arr = stack.pop(); stack.push((int)(byte) Array.getByte(arr, i)); break; }
                    case 0xEB: { byte val = (byte) unboxI(stack.pop()); int i = unboxI(stack.pop()); Object arr = stack.pop(); Array.setByte(arr, i, val); break; }
                    case 0xEC: { int i = unboxI(stack.pop()); Object arr = stack.pop(); stack.push((int)(char) Array.getChar(arr, i)); break; }
                    case 0xED: { char val = (char) unboxI(stack.pop()); int i = unboxI(stack.pop()); Object arr = stack.pop(); Array.setChar(arr, i, val); break; }
                    case 0xEE: { int i = unboxI(stack.pop()); Object arr = stack.pop(); stack.push((int)(short) Array.getShort(arr, i)); break; }
                    case 0xEF: { short val = (short) unboxI(stack.pop()); int i = unboxI(stack.pop()); Object arr = stack.pop(); Array.setShort(arr, i, val); break; }
                    case 0xF0: { // NEWARRAY
                        int type = buf.get() & 0xFF;
                        int len = unboxI(stack.pop());
                        stack.push(newPrimitiveArray(type, len));
                        break;
                    }
                    case 0xF1: { // ANEWARRAY
                        String cls = readString(buf);
                        int len = unboxI(stack.pop());
                        stack.push(Array.newInstance(classFor(cache, cls), len));
                        break;
                    }

                    default:
                        throw new IllegalStateException("Unknown VM opcode: 0x" + Integer.toHexString(op & 0xFF)
                                + " at position " + (buf.position() - 1));
                }
            }
        } catch (VMReturnException ret) {
            return ret.value;
        } catch (Throwable t) {
            throw new RuntimeException("VM execution error at pc=" + buf.position(), t);
        }

        return null; // implicit void return
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static String readString(ByteBuffer buf) {
        int len = buf.getShort() & 0xFFFF;
        byte[] bytes = new byte[len];
        buf.get(bytes);
        return new String(bytes, java.nio.charset.StandardCharsets.UTF_8);
    }

    private static int    unboxI(Object o) { return o instanceof Integer i ? i : o instanceof Number n ? n.intValue() : 0; }
    private static long   unboxL(Object o) { return o instanceof Long l ? l : o instanceof Number n ? n.longValue() : 0L; }
    private static float  unboxF(Object o) { return o instanceof Float f ? f : o instanceof Number n ? n.floatValue() : 0f; }
    private static double unboxD(Object o) { return o instanceof Double d ? d : o instanceof Number n ? n.doubleValue() : 0.0; }

    private static Class<?> classFor(Map<String, Object> cache, String internal) throws ClassNotFoundException {
        String key = "C:" + internal;
        Class<?> c = (Class<?>) cache.get(key);
        if (c == null) {
            c = Class.forName(internal.replace('/', '.'));
            cache.put(key, c);
        }
        return c;
    }

    private static void executeInvoke(Deque<Object> stack, Map<String, Object> cache,
                                       ByteBuffer buf, boolean isStatic,
                                       boolean isVirtual, boolean isInterface) throws Exception {
        final String owner = readString(buf);
        final String name  = readString(buf);
        final String desc  = readString(buf);

        final String cacheKey = (isStatic ? "MS:" : "MI:") + owner + "." + name + desc;

        Method method = (Method) cache.get(cacheKey);
        if (method == null) {
            Class<?> cls = classFor(cache, owner);
            // Walk hierarchy to find method matching descriptor
            method = findMethod(cls, name, desc);
            method.setAccessible(true);
            cache.put(cacheKey, method);
        }

        // Collect arguments from stack (reverse order)
        final Class<?>[] paramTypes = method.getParameterTypes();
        final Object[] callArgs = new Object[paramTypes.length];
        for (int i = paramTypes.length - 1; i >= 0; i--) {
            callArgs[i] = coerce(stack.pop(), paramTypes[i]);
        }

        Object receiver = isStatic ? null : stack.pop();

        // Handle NEW + invokespecial <init>: receiver might be a Class placeholder
        if (receiver instanceof Class<?> cls && name.equals("<init>")) {
            receiver = cls.getDeclaredConstructors()[0]; // We need the constructor
            // Find matching constructor
            Constructor<?> ctor = findConstructor(cls, desc);
            ctor.setAccessible(true);
            Object newInstance = ctor.newInstance(callArgs);
            stack.push(newInstance);
            return;
        }

        Object result = method.invoke(receiver, callArgs);

        if (method.getReturnType() != void.class) {
            stack.push(result);
        }
    }

    private static void executeGetField(Deque<Object> stack, Map<String, Object> cache,
                                         ByteBuffer buf, boolean isStatic) throws Exception {
        final String owner = readString(buf);
        final String name  = readString(buf);
        readString(buf); // desc — unused for get

        final String cacheKey = (isStatic ? "FS:" : "FI:") + owner + "." + name;
        Field field = (Field) cache.get(cacheKey);
        if (field == null) {
            field = findField(classFor(cache, owner), name);
            field.setAccessible(true);
            cache.put(cacheKey, field);
        }

        Object receiver = isStatic ? null : stack.pop();
        stack.push(field.get(receiver));
    }

    private static void executePutField(Deque<Object> stack, Map<String, Object> cache,
                                         ByteBuffer buf, boolean isStatic) throws Exception {
        final String owner = readString(buf);
        final String name  = readString(buf);
        readString(buf); // desc

        final String cacheKey = (isStatic ? "FS:" : "FI:") + owner + "." + name;
        Field field = (Field) cache.get(cacheKey);
        if (field == null) {
            field = findField(classFor(cache, owner), name);
            field.setAccessible(true);
            cache.put(cacheKey, field);
        }

        Object value = stack.pop();
        Object receiver = isStatic ? null : stack.pop();
        field.set(receiver, coerce(value, field.getType()));
    }

    private static Method findMethod(Class<?> cls, String name, String desc) throws NoSuchMethodException {
        for (Class<?> c = cls; c != null; c = c.getSuperclass()) {
            for (Method m : c.getDeclaredMethods()) {
                if (m.getName().equals(name) && descMatches(m, desc)) return m;
            }
        }
        for (Class<?> iface : cls.getInterfaces()) {
            for (Method m : iface.getDeclaredMethods()) {
                if (m.getName().equals(name) && descMatches(m, desc)) return m;
            }
        }
        throw new NoSuchMethodException(cls.getName() + "." + name + desc);
    }

    private static Constructor<?> findConstructor(Class<?> cls, String desc) throws NoSuchMethodException {
        for (Constructor<?> c : cls.getDeclaredConstructors()) {
            if (ctorDescMatches(c, desc)) return c;
        }
        throw new NoSuchMethodException(cls.getName() + ".<init>" + desc);
    }

    private static Field findField(Class<?> cls, String name) throws NoSuchFieldException {
        for (Class<?> c = cls; c != null; c = c.getSuperclass()) {
            try { return c.getDeclaredField(name); } catch (NoSuchFieldException ignored) {}
        }
        throw new NoSuchFieldException(cls.getName() + "." + name);
    }

    private static boolean descMatches(Method m, String desc) {
        return buildMethodDescriptor(m).equals(desc);
    }

    private static boolean ctorDescMatches(Constructor<?> c, String desc) {
        return buildCtorDescriptor(c).equals(desc);
    }

    private static String buildMethodDescriptor(Method m) {
        StringBuilder sb = new StringBuilder("(");
        for (Class<?> p : m.getParameterTypes()) appendTypeDesc(sb, p);
        sb.append(')');
        appendTypeDesc(sb, m.getReturnType());
        return sb.toString();
    }

    private static String buildCtorDescriptor(Constructor<?> c) {
        StringBuilder sb = new StringBuilder("(");
        for (Class<?> p : c.getParameterTypes()) appendTypeDesc(sb, p);
        sb.append(")V");
        return sb.toString();
    }

    /**
     * Appends the JVM type descriptor for {@code c} to {@code sb}.
     * Handles primitives, void, arrays (any depth), and reference types.
     * No external dependencies — pure Java reflection.
     */
    private static void appendTypeDesc(StringBuilder sb, Class<?> c) {
        if (c == void.class)    { sb.append('V'); return; }
        if (c == boolean.class) { sb.append('Z'); return; }
        if (c == byte.class)    { sb.append('B'); return; }
        if (c == char.class)    { sb.append('C'); return; }
        if (c == short.class)   { sb.append('S'); return; }
        if (c == int.class)     { sb.append('I'); return; }
        if (c == long.class)    { sb.append('J'); return; }
        if (c == float.class)   { sb.append('F'); return; }
        if (c == double.class)  { sb.append('D'); return; }
        if (c.isArray()) {
            // Class.getName() for arrays is already JVM format ([I, [[I, [Ljava.lang.String; ...)
            // Just replace '.' with '/' for reference component types.
            sb.append(c.getName().replace('.', '/'));
            return;
        }
        // Reference type: Ljava/lang/String;
        sb.append('L').append(c.getName().replace('.', '/')).append(';');
    }

    private static Object coerce(Object val, Class<?> target) {
        if (val == null || !target.isPrimitive()) return val;
        if (target == int.class)    return unboxI(val);
        if (target == long.class)   return unboxL(val);
        if (target == float.class)  return unboxF(val);
        if (target == double.class) return unboxD(val);
        if (target == boolean.class) return unboxI(val) != 0;
        if (target == byte.class)   return (byte) unboxI(val);
        if (target == char.class)   return (char) unboxI(val);
        if (target == short.class)  return (short) unboxI(val);
        return val;
    }

    private static Object newPrimitiveArray(int type, int len) {
        return switch (type) {
            case 4  -> new boolean[len];
            case 5  -> new char[len];
            case 6  -> new float[len];
            case 7  -> new double[len];
            case 8  -> new byte[len];
            case 9  -> new short[len];
            case 10 -> new int[len];
            case 11 -> new long[len];
            default -> throw new IllegalArgumentException("Unknown array type: " + type);
        };
    }

    /** Internal exception used to implement early-return from deeply nested dispatch. */
    private static final class VMReturnException extends RuntimeException {
        final Object value;
        VMReturnException(Object value) { super(null, null, true, false); this.value = value; }
    }
}
