package dev.sweety.sql4j.processor;

import com.google.auto.service.AutoService;
import com.squareup.javapoet.*;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

@SupportedAnnotationTypes({
    "dev.sweety.sql4j.api.obj.Table.Info",
    "dev.sweety.sql4j.api.obj.Column.Info",
    "dev.sweety.sql4j.api.obj.annotation.ManyToOne",
    "dev.sweety.sql4j.api.obj.annotation.OneToMany",
    "dev.sweety.sql4j.api.obj.annotation.ManyToMany"
})
@SupportedSourceVersion(SourceVersion.RELEASE_11)
@AutoService(Processor.class)
public class SQL4JProcessor extends AbstractProcessor {

    private static final String TABLE_INFO = "dev.sweety.sql4j.api.obj.Table.Info";
    private static final String COLUMN_INFO = "dev.sweety.sql4j.api.obj.Column.Info";
    private static final String MANY_TO_ONE = "dev.sweety.sql4j.api.obj.annotation.ManyToOne";
    private static final String ONE_TO_MANY = "dev.sweety.sql4j.api.obj.annotation.OneToMany";
    private static final String MANY_TO_MANY = "dev.sweety.sql4j.api.obj.annotation.ManyToMany";
    
    private static final String TABLE_REGISTRY = "dev.sweety.sql4j.api.obj.table.TableRegistry";
    private static final String COLUMN = "dev.sweety.sql4j.api.obj.Column";
    private static final String TABLE_ACCESSOR = "dev.sweety.sql4j.api.obj.TableAccessor";
    private static final String TABLE_RELATION = "dev.sweety.sql4j.api.obj.Table.Relation";

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        TypeElement tableInfoType = processingEnv.getElementUtils().getTypeElement(TABLE_INFO);
        if (tableInfoType == null) return false;

        for (Element element : roundEnv.getElementsAnnotatedWith(tableInfoType)) {
            if (element.getKind() == ElementKind.CLASS) {
                try {
                    generateMirrorClass((TypeElement) element);
                } catch (IOException e) {
                    if (!e.getMessage().contains("Attempt to recreate a file")) {
                        processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, "Failed to generate table class: " + e.getMessage());
                    }
                }
            }
        }
        return true;
    }

    private void generateMirrorClass(TypeElement typeElement) throws IOException {
        String packageName = processingEnv.getElementUtils().getPackageOf(typeElement).getQualifiedName().toString();
        String simpleName = typeElement.getSimpleName().toString();
        
        String mirrorName = simpleName + "Table";
        Element enclosing = typeElement.getEnclosingElement();
        while (enclosing != null && enclosing.getKind() == ElementKind.CLASS) {
            mirrorName = enclosing.getSimpleName().toString() + "_" + mirrorName;
            enclosing = enclosing.getEnclosingElement();
        }

        ClassName entityClass = ClassName.get(typeElement);
        ClassName columnClass = ClassName.bestGuess(COLUMN);
        ClassName registryClass = ClassName.bestGuess(TABLE_REGISTRY);
        ClassName accessorInterface = ClassName.bestGuess(TABLE_ACCESSOR);
        ClassName relationClass = ClassName.bestGuess(TABLE_RELATION);

        TypeSpec.Builder mirrorBuilder = TypeSpec.classBuilder(mirrorName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(ParameterizedTypeName.get(accessorInterface, entityClass))
                .addJavadoc("Generated by SQL4J Processor. Do not modify.\n");

        mirrorBuilder.addField(FieldSpec.builder(ClassName.get(packageName, mirrorName), "INSTANCE")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer("new $L()", mirrorName)
                .build());

        // Extract table name
        String tableName = simpleName.toLowerCase();
        for (AnnotationMirror am : typeElement.getAnnotationMirrors()) {
            if (am.getAnnotationType().toString().equals(TABLE_INFO)) {
                for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : am.getElementValues().entrySet()) {
                    if (entry.getKey().getSimpleName().toString().equals("name") && !entry.getValue().getValue().toString().isEmpty()) {
                        tableName = entry.getValue().getValue().toString();
                    }
                }
            }
        }

        mirrorBuilder.addField(FieldSpec.builder(String.class, "TABLE_NAME")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer("$S", tableName)
                .build());

        List<FieldData> fields = new ArrayList<>();

        for (Element enclosed : typeElement.getEnclosedElements()) {
            if (enclosed.getKind() == ElementKind.FIELD) {
                VariableElement field = (VariableElement) enclosed;
                String fieldName = field.getSimpleName().toString();
                boolean isPrivate = field.getModifiers().contains(Modifier.PRIVATE);

                // Column detection
                AnnotationMirror colAnn = getAnnotation(field, COLUMN_INFO);
                AnnotationMirror mtoAnn = getAnnotation(field, MANY_TO_ONE);
                AnnotationMirror otmAnn = getAnnotation(field, ONE_TO_MANY);
                AnnotationMirror mtmAnn = getAnnotation(field, MANY_TO_MANY);

                if (colAnn != null || mtoAnn != null) {
                    String colName = fieldName;
                    if (colAnn != null) {
                        String annName = getAnnotationValue(colAnn, "name");
                        if (annName != null && !annName.isEmpty()) colName = annName;
                    } else if (mtoAnn != null) {
                        String annName = getAnnotationValue(mtoAnn, "columnName");
                        colName = (annName != null && !annName.isEmpty()) ? annName : fieldName + "_id";
                    }

                    TypeName fieldType = TypeName.get(field.asType());
                    TypeName boxedType = fieldType.isPrimitive() ? fieldType.box() : fieldType;

                    FieldData fd = new FieldData(fieldName, colName, fieldType, boxedType, isPrivate);
                    fields.add(fd);

                    // Static Column reference
                    mirrorBuilder.addField(FieldSpec.builder(ParameterizedTypeName.get(columnClass, boxedType), fieldName.toUpperCase())
                            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                            .initializer("($T<$T>) $T.getDefault().get($T.class).column($S)", 
                                    columnClass, boxedType, registryClass, entityClass, colName)
                            .build());

                    // Field cache for both private and relation fields
                    mirrorBuilder.addField(FieldSpec.builder(java.lang.reflect.Field.class, "FIELD_" + fieldName)
                            .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                            .initializer("getPrivateField($T.class, $S)", entityClass, fieldName)
                            .build());

                    // Individual Accessors
                    mirrorBuilder.addMethod(buildGetter(entityClass, fd));
                    mirrorBuilder.addMethod(buildSetter(entityClass, fd));
                }

                // Relation detection
                if (mtoAnn != null || otmAnn != null || mtmAnn != null) {
                    if (getAnnotation(field, COLUMN_INFO) == null && getAnnotation(field, MANY_TO_ONE) == null) {
                        // Field cache for non-column relations
                        mirrorBuilder.addField(FieldSpec.builder(java.lang.reflect.Field.class, "FIELD_" + fieldName)
                                .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                                .initializer("getPrivateField($T.class, $S)", entityClass, fieldName)
                                .build());
                    }

                    String relType;
                    String mappedBy = null;
                    if (mtoAnn != null) relType = "MANY_TO_ONE";
                    else if (otmAnn != null) {
                        relType = "ONE_TO_MANY";
                        mappedBy = getAnnotationValue(otmAnn, "mappedBy");
                    } else {
                        relType = "MANY_TO_MANY";
                    }

                    TypeName targetClass = getTargetClass(field);
                    String colRef = (mtoAnn != null) ? fieldName.toUpperCase() : "null";
                    mirrorBuilder.addField(FieldSpec.builder(relationClass, fieldName.toUpperCase() + "_REL")
                            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                            .initializer("new $T($T.Type.$L, FIELD_$L, $T.class, $S, null, $L)",
                                    relationClass, relationClass, relType, fieldName, targetClass, mappedBy, colRef)
                            .build());
                }
            }
        }

        // Static SQL Generation
        String allCols = fields.stream().map(f -> f.colName).collect(Collectors.joining(", "));
        String placeholders = fields.stream().map(_ -> "?").collect(Collectors.joining(", "));
        mirrorBuilder.addMethod(MethodSpec.methodBuilder("getSelectAllSql")
                .addAnnotation(Override.class).addModifiers(Modifier.PUBLIC).returns(String.class)
                .addStatement("return $S", "SELECT " + allCols + " FROM " + tableName).build());

        mirrorBuilder.addMethod(MethodSpec.methodBuilder("getInsertSql")
                .addAnnotation(Override.class).addModifiers(Modifier.PUBLIC).returns(String.class)
                .addStatement("return $S", "INSERT INTO " + tableName + " (" + allCols + ") VALUES (" + placeholders + ")").build());

        mirrorBuilder.addMethod(MethodSpec.methodBuilder("newInstance")
                .addAnnotation(Override.class).addModifiers(Modifier.PUBLIC).returns(entityClass)
                .addStatement("return new $T()", entityClass).build());

        // Dispatchers
        mirrorBuilder.addMethod(buildDispatcher("setFieldValue", entityClass, fields, true));
        mirrorBuilder.addMethod(buildDispatcher("getFieldValue", entityClass, fields, false));

        // Helper for private fields
        mirrorBuilder.addMethod(MethodSpec.methodBuilder("getPrivateField")
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                .addParameter(Class.class, "clazz")
                .addParameter(String.class, "name")
                .returns(java.lang.reflect.Field.class)
                .addCode("try {\n" +
                        "    java.lang.reflect.Field f = clazz.getDeclaredField(name);\n" +
                        "    f.setAccessible(true);\n" +
                        "    return f;\n" +
                        "} catch (Exception e) { throw new RuntimeException(e); }\n")
                .build());

        JavaFile javaFile = JavaFile.builder(packageName, mirrorBuilder.build()).build();
        javaFile.writeTo(processingEnv.getFiler());
    }

    private MethodSpec buildGetter(ClassName entityClass, FieldData fd) {
        MethodSpec.Builder mb = MethodSpec.methodBuilder("get_" + fd.fieldName)
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(entityClass, "instance")
                .returns(fd.fieldType);
        mb.beginControlFlow("try")
          .addStatement("return ($T) FIELD_$L.get(instance)", fd.boxedType, fd.fieldName)
          .nextControlFlow("catch (Exception e)")
          .addStatement("throw new RuntimeException(e)")
          .endControlFlow();
        return mb.build();
    }

    private MethodSpec buildSetter(ClassName entityClass, FieldData fd) {
        MethodSpec.Builder mb = MethodSpec.methodBuilder("set_" + fd.fieldName)
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(entityClass, "instance")
                .addParameter(fd.fieldType, "value");
        mb.beginControlFlow("try")
          .addStatement("FIELD_$L.set(instance, value)", fd.fieldName)
          .nextControlFlow("catch (Exception e)")
          .addStatement("throw new RuntimeException(e)")
          .endControlFlow();
        return mb.build();
    }

    private MethodSpec buildDispatcher(String name, ClassName entityClass, List<FieldData> fields, boolean isSetter) {
        MethodSpec.Builder mb = MethodSpec.methodBuilder(name)
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(entityClass, "instance")
                .addParameter(String.class, "colName");
        
        if (isSetter) mb.addParameter(Object.class, "value");
        else mb.returns(Object.class);

        CodeBlock.Builder block = CodeBlock.builder().beginControlFlow("switch (colName.toLowerCase())");
        for (FieldData fd : fields) {
            block.add("case $S:\n", fd.colName.toLowerCase());
            block.indent();
            if (isSetter) {
                block.addStatement("set_$L(instance, ($T) value)", fd.fieldName, fd.fieldType);
                block.addStatement("break");
            } else {
                block.addStatement("return get_$L(instance)", fd.fieldName);
            }
            block.unindent();
        }
        if (!isSetter) block.add("default:\n").indent().addStatement("return null").unindent();
        block.endControlFlow();
        return mb.addCode(block.build()).build();
    }

    private AnnotationMirror getAnnotation(Element element, String typeName) {
        for (AnnotationMirror am : element.getAnnotationMirrors()) {
            if (am.getAnnotationType().toString().equals(typeName)) return am;
        }
        return null;
    }

    private String getAnnotationValue(AnnotationMirror am, String key) {
        for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : am.getElementValues().entrySet()) {
            if (entry.getKey().getSimpleName().toString().equals(key)) return entry.getValue().getValue().toString();
        }
        return null;
    }

    private TypeName getTargetClass(VariableElement field) {
        TypeMirror type = field.asType();
        if (type instanceof DeclaredType dt) {
            List<? extends TypeMirror> typeArgs = dt.getTypeArguments();
            if (!typeArgs.isEmpty()) return TypeName.get(typeArgs.get(0));
        }
        return TypeName.get(type);
    }

    private static class FieldData {
        final String fieldName;
        final String colName;
        final TypeName fieldType;
        final TypeName boxedType;
        final boolean isPrivate;

        FieldData(String fieldName, String colName, TypeName fieldType, TypeName boxedType, boolean isPrivate) {
            this.fieldName = fieldName;
            this.colName = colName;
            this.fieldType = fieldType;
            this.boxedType = boxedType;
            this.isPrivate = isPrivate;
        }
    }
}
