plugins {
    id 'com.gradleup.shadow' version '9.3.1'
}

configurations {
    shadowInclude
    compileOnly.extendsFrom(shadowInclude)
}

dependencies {
    shadowInclude 'org.ow2.asm:asm:9.6'
    shadowInclude 'org.ow2.asm:asm-commons:9.6'
    shadowInclude 'org.ow2.asm:asm-tree:9.6'
    shadowInclude 'org.ow2.asm:asm-analysis:9.6'
    shadowInclude 'org.ow2.asm:asm-util:9.6'
}

tasks.named('shadowJar') {
    archiveClassifier.set('all')
    manifest {
        attributes 'Main-Class': 'dev.sweety.transform.TransformCLI'
    }
    configurations = [project.configurations.runtimeClasspath, project.configurations.shadowInclude]
}
