pluginManager.withPlugin('org.jetbrains.kotlin.jvm') {
    kotlin.sourceSets.configureEach {
        kotlin.srcDirs = []
    }
    tasks.named('jar') {
        setDependsOn(dependsOn.toList().findAll { it.toString() != 'compileKotlin' })
    }
}

dependencies {
    implementation project(':feature:module:extension:api')
    implementation project(':feature:module:versioning:protocol')
    implementation project(':util:logger')
}
