package dev.sweety.sql4j.api.query;

import dev.sweety.sql4j.api.exception.Sql4jQueryException;
import dev.sweety.sql4j.api.obj.Row;
import dev.sweety.sql4j.api.obj.Table;
import dev.sweety.sql4j.api.query.functions.QueryBinder;
import dev.sweety.sql4j.api.query.functions.QueryExecutor;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Function;

/**
 * A general-purpose {@link Query} backed by a raw SQL string and a configurable executor.
 *
 * <h3>Two construction styles</h3>
 * <ol>
 *   <li><b>Entity-mapping constructors</b> — used by generated repository implementations:
 *       <pre>{@code new ParamQuery<>(sql, params, table)}</pre>
 *   </li>
 *   <li><b>Builder</b> — used internally for ad-hoc queries with arbitrary executors:
 *       <pre>{@code ParamQuery.<List<Row>>builder(sql, ps -> ...).bind(...).build()}</pre>
 *   </li>
 * </ol>
 */
public final class ParamQuery<T> extends AbstractQuery<T> {

    private final String sql;
    // Entity-mapping mode fields
    private final List<Object> params;
    private final Function<Row, ?> mapper;
    private final Table<?> table;
    // Builder mode fields
    private final QueryBinder binder;
    private final QueryExecutor<T> executor;
    private final boolean returnGeneratedKeys;
    // Discriminator
    private final boolean builderMode;
    // Optional post-execution action (e.g. cache eviction generated by @CacheEvict)
    private Consumer<T> postAction;

    // ─── Entity-mapping constructors (used by generated code) ──────────────────

    /**
     * Creates a {@code ParamQuery} that maps each result row to an entity via the table descriptor.
     *
     * @param sql    the SQL string (may contain {@code ?} placeholders)
     * @param params the bound parameter values, in order
     * @param table  the table descriptor used for entity construction
     */
    public ParamQuery(String sql, List<Object> params, Table<T> table) {
        this.sql = sql;
        this.params = params;
        this.table = table;
        this.mapper = null;
        this.binder = null;
        this.executor = null;
        this.returnGeneratedKeys = false;
        this.builderMode = false;
    }

    /**
     * Creates a {@code ParamQuery} that maps each result row to a custom type via {@code mapper}.
     *
     * @param sql    the SQL string
     * @param params the bound parameter values
     * @param mapper a per-row mapping function
     */
    public ParamQuery(String sql, List<Object> params, Function<Row, T> mapper) {
        this.sql = sql;
        this.params = params;
        this.mapper = mapper;
        this.table = null;
        this.binder = null;
        this.executor = null;
        this.returnGeneratedKeys = false;
        this.builderMode = false;
    }

    // ─── Builder constructor (internal/api use) ─────────────────────────────────

    private ParamQuery(Builder<T> b) {
        this.sql = b.sql;
        this.binder = b.binder;
        this.executor = b.executor;
        this.returnGeneratedKeys = b.returnGeneratedKeys;
        this.params = null;
        this.mapper = null;
        this.table = null;
        this.builderMode = true;
    }

    // ─── Post-action (cache eviction, etc.) ─────────────────────────────────────

    /**
     * Registers an action to run synchronously after this query completes, with the
     * query result as argument. Used by generated code for {@code @CacheEvict} methods.
     *
     * @return {@code this} for fluent chaining
     */
    public ParamQuery<T> withPostAction(Consumer<T> action) {
        this.postAction = action;
        return this;
    }

    // ─── Builder factory ─────────────────────────────────────────────────────────

    /**
     * Returns a builder for an ad-hoc query with a custom executor.
     *
     * @param <T>      return type of the query
     * @param sql      the SQL string
     * @param executor the result-set executor
     */
    public static <T> Builder<T> builder(String sql, QueryExecutor<T> executor) {
        return new Builder<>(sql, executor);
    }

    /**
     * Returns a builder pre-configured for {@code SELECT} queries that return {@code List<Row>}.
     */
    public static Builder<List<Row>> rowBuilder(String sql) {
        return new Builder<>(sql, ps -> {
            try (ResultSet rs = ps.executeQuery()) {
                return Row.fromResultSetAll(rs);
            }
        });
    }

    // ─── Builder ─────────────────────────────────────────────────────────────────

    /** Fluent builder for {@link ParamQuery}. */
    public static final class Builder<T> {
        private final String sql;
        private final QueryExecutor<T> executor;
        private QueryBinder binder = QueryBinder.EMPTY;
        private boolean returnGeneratedKeys = false;

        Builder(String sql, QueryExecutor<T> executor) {
            this.sql = sql;
            this.executor = executor;
        }

        /** Sets the parameter binder. */
        public Builder<T> bind(QueryBinder binder) {
            this.binder = binder;
            return this;
        }

        /** Requests that generated keys be returned after execution. */
        public Builder<T> returnGeneratedKeys() {
            this.returnGeneratedKeys = true;
            return this;
        }

        /** Builds the {@link ParamQuery}. */
        public ParamQuery<T> build() {
            if (sql == null || sql.isBlank()) throw new Sql4jQueryException("ParamQuery.Builder: sql is required");
            if (executor == null) throw new Sql4jQueryException("ParamQuery.Builder: executor is required");
            return new ParamQuery<>(this);
        }
    }

    // ─── Query implementation ─────────────────────────────────────────────────────

    @Override
    protected String buildSql() {
        return sql;
    }

    @Override
    public void bind(PreparedStatement ps) throws SQLException {
        if (builderMode) {
            if (binder != null) binder.bind(ps);
        } else {
            if (params != null) {
                for (int i = 0; i < params.size(); i++) {
                    ps.setObject(i + 1, params.get(i));
                }
            }
        }
    }

    @Override
    @SuppressWarnings("unchecked")
    public T execute(PreparedStatement ps) throws SQLException {
        T result;
        if (builderMode) {
            result = executor.execute(ps);
        } else {
            try (ResultSet rs = ps.executeQuery()) {
                List<Row> rows = Row.fromResultSetAll(rs);
                if (table != null) {
                    List<Object> entities = new ArrayList<>();
                    for (Row row : rows) {
                        entities.add(row.extractEntity((Table<Object>) table, ""));
                    }
                    result = (T) entities;
                } else if (mapper != null) {
                    List<Object> mapped = new ArrayList<>();
                    for (Row row : rows) {
                        mapped.add(mapper.apply(row));
                    }
                    result = (T) mapped;
                } else {
                    result = (T) rows;
                }
            }
        }
        if (postAction != null) postAction.accept(result);
        return result;
    }

    @Override
    public boolean returnGeneratedKeys() {
        return returnGeneratedKeys;
    }
}
